const info2 = {
  "code": 0,
  "message": "",
  "result": {
    "list": [
      {
        "id": 1,
        "username": "Jack",
        "sex": 2,
        "age": 45,
        "state": 4,
        "interest": 5,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 2,
        "username": "Jack",
        "sex": 1,
        "age": 29,
        "state": 3,
        "interest": 6,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 3,
        "username": "Jack",
        "sex": 2,
        "age": 40,
        "state": 2,
        "interest": 7,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 4,
        "username": "Jack",
        "sex": 2,
        "age": 14,
        "state": 2,
        "interest": 6,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 5,
        "username": "Jack",
        "sex": 2,
        "age": 28,
        "state": 2,
        "interest": 7,
        "isMarried1": 1,
        "isMarried2": 0,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 6,
        "username": "Jack",
        "sex": 1,
        "age": 45,
        "state": 3,
        "interest": 4,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 7,
        "username": "Jack",
        "sex": 2,
        "age": 41,
        "state": 4,
        "interest": 7,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 8,
        "username": "Jack",
        "sex": 1,
        "age": 24,
        "state": 2,
        "interest": 7,
        "isMarried1": 1,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 9,
        "username": "Jack",
        "sex": 2,
        "age": 49,
        "state": 2,
        "interest": 5,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 10,
        "username": "Jack",
        "sex": 1,
        "age": 20,
        "state": 4,
        "interest": 5,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 11,
        "username": "Jack",
        "sex": 1,
        "age": 20,
        "state": 1,
        "interest": 4,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 12,
        "username": "Jack",
        "sex": 1,
        "age": 17,
        "state": 3,
        "interest": 5,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 13,
        "username": "Jack",
        "sex": 1,
        "age": 38,
        "state": 2,
        "interest": 5,
        "isMarried1": 1,
        "isMarried2": 0,
        "isMarried3": 0,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 14,
        "username": "Jack",
        "sex": 2,
        "age": 30,
        "state": 4,
        "interest": 6,
        "isMarried1": 1,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 15,
        "username": "Jack",
        "sex": 1,
        "age": 38,
        "state": 4,
        "interest": 3,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 16,
        "username": "Jack",
        "sex": 2,
        "age": 14,
        "state": 2,
        "interest": 5,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 17,
        "username": "Jack",
        "sex": 2,
        "age": 31,
        "state": 4,
        "interest": 3,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 0,
        "isMarried4": 1,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 18,
        "username": "Jack",
        "sex": 2,
        "age": 42,
        "state": 5,
        "interest": 8,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 19,
        "username": "Jack",
        "sex": 2,
        "age": 23,
        "state": 4,
        "interest": 2,
        "isMarried1": 1,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 20,
        "username": "Jack",
        "sex": 2,
        "age": 14,
        "state": 2,
        "interest": 3,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 0,
        "isMarried7": 0,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 21,
        "username": "Jack",
        "sex": 1,
        "age": 37,
        "state": 3,
        "interest": 4,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 22,
        "username": "Jack",
        "sex": 1,
        "age": 15,
        "state": 2,
        "interest": 1,
        "isMarried1": 0,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 0,
        "isMarried5": 1,
        "isMarried6": 0,
        "isMarried7": 1,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 23,
        "username": "Jack",
        "sex": 2,
        "age": 47,
        "state": 3,
        "interest": 7,
        "isMarried1": 1,
        "isMarried2": 1,
        "isMarried3": 0,
        "isMarried4": 1,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 0,
        "isMarried8": 0,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 24,
        "username": "Jack",
        "sex": 1,
        "age": 39,
        "state": 3,
        "interest": 4,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 0,
        "isMarried5": 1,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      },
      {
        "id": 25,
        "username": "Jack",
        "sex": 2,
        "age": 30,
        "state": 3,
        "interest": 7,
        "isMarried1": 0,
        "isMarried2": 0,
        "isMarried3": 1,
        "isMarried4": 1,
        "isMarried5": 0,
        "isMarried6": 1,
        "isMarried7": 1,
        "isMarried8": 1,
        "birthday": "2000-01-01",
        "address": "北京市海淀区",
        "time": "09:00:00"
      }
    ],
    "page": 2,
    "page_size": 5,
    "total_count": 30
  }
}
export default info2;